M19G1/Models/AddFacilityViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M19G1.Models
{
    public class AddFacilityViewModel
    {
        public BookingViewModel Booking { get; set; }

        [Display(Name = "Room Name ")]
        [Required(ErrorMessage = "A room should be specified !")]
        public int RoomId { get; set; }

        [Display(Name ="Facility")]
        [Required(ErrorMessage ="A facility should be specified !")]
        public int FacilityId { get; set; }
        public List<FacilityModel> Facilities { get; set; }

        [Display(Name ="Quantity")]
        [Range(1,5,ErrorMessage ="Quantity must be between 1 and 5")]
        public int FacilityQuantity { get; set; }

    }
}

M19G1/Models/ChooseRoomViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M19G1.Models
{
    public class ChooseRoomViewModel
    {
        public BookingModel booking { get; set; }

        [Display(Name = "Room ")]
        [Required(ErrorMessage = "Room should be specified !")]
        public int RoomId { get; set; }
        public List<RoomModel> rooms { get; set; }

        [Display(Name = "Extra facilities ")]
        public int[] facilityIds { get; set; }
        public List<FacilityModel> facilities { get; set; }
    }
}

M19G1/Models/ClientViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace M19G1.Models
{
    public class UserClientViewModel
    {

        [Required(ErrorMessage = "Firstname is required")]
        [StringLength(30, MinimumLength = 3,
        ErrorMessage = "Firstname Should be minimum 3 characters and a maximum of 30 characters")]
        [DataType(DataType.Text)]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Lastname is required")]
        [StringLength(30, MinimumLength = 3,
        ErrorMessage = "Lastname Should be minimum 3 characters and a maximum of 30 characters")]
        [DataType(DataType.Text)]
        public string LastName { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [StringLength(30, MinimumLength = 3,
        ErrorMessage = "Username Should be minimum 3 characters and a maximum of 30 characters")]
        public string Username { get; set; }
        public DateTime Birthday { get; set; }
        public string Gender { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmedPassword { get; set; }
    }
}

M19G1/Models/CreateBookingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M19G1.Models
{
    public class CreateBookingViewModel
    {
        [Display(Name = "Start date ")]
        [BookingDate(ErrorMessage = "Booking start date should be between next 2 hours and 30 days")]
        [Required(ErrorMessage ="Start date should be specified !")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End date ")]
        [Required(ErrorMessage ="End date should be specified !")]
        public DateTime EndDate { get; set; }

        [Display(Name ="Initial pick up location ")]
        public string InitialLocation { get; set; }
        [Display(Name ="Final drop off location ")]
        public string FinalLocation { get; set; }
    }
}

M19G1/Models/FilterRoomViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M19G1.Models
{
    public class FilterRoomViewModel
    {
        [Display(Name = "Category")]
        public int? CategoryId { get; set; }
        public List<RoomCategoryModel> Categories { get; set; }

        [Display(Name ="Room Name")]
        public string Name { get; set; }

        [Display(Name = "Max Price")]
        [Range(0.0,1000.0,ErrorMessage = "Price must be between 0 and 1000")]
        public decimal? Price { get; set; }

        [Display(Name ="Occupied")]
        public bool Occupied { get; set; }

        [Display(Name ="Facility List")]
        public int[] SelectedFacilities { get; set; }
        public List<FacilityModel> Facilities { get; set; }

        public List<RoomModel> Rooms { get; set; }
    }
}

M19G1/Models/RoomDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M19G1.Models
{
    public class RoomDetailsViewModel
    {
        [Display(Name ="Room Name")]
        public string RoomName { get; set; }
        [Display(Name = "Number of Guests")]
        public int GuestsNr { get; set; }
        [Display(Name = "Price")]
        public decimal Price { get; set; }
        [Display(Name = "Description")]
        public string RoomDescription { get; set; }
        public RoomCategoryModel RoomCategory { get; set; }
        public List<RoomFacilityModel> RoomFacilities { get; set; }
    }
}

M19G1/Controllers/ClientsController.cs
using M19G1.IBLL;
using M19G1.Mappings;
using M19G1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace M19G1.Controllers
{
    public class ClientsController : BaseController
    {
        private readonly IBookingService _bookingService;
        private readonly IFacilityService _facilityService;
        private readonly IRoomCategoryService _roomCategoryService;
        private readonly IRoomService _roomService;
        private readonly IDriverService _driverService;
        private readonly IRatingService _ratingService;
        public ClientsController(IBookingService bookingService,IFacilityService facilityService, 
            IRoomCategoryService roomCategoryService, IRoomService roomService, IDriverService driverService,
            IRatingService ratingService)
        {
            _bookingService = bookingService;
            _facilityService = facilityService;
            _roomCategoryService = roomCategoryService;
            _roomService = roomService;
            _driverService = driverService;
            _ratingService = ratingService;

        }
        // GET: Admin
        public ActionResult Index()
        {
            return RedirectToAction("ActiveBookings");
        }

        [HttpGet]
        public ActionResult OldBookings()
        {
            List<BookingModel> oldBookings = _bookingService.GetOldBookings(6);//CurrentUser.Id
            List<BookingElementViewModel> oldBookingsElements = oldBookings.Select(b => BookingMappings.MapBookingModelToViewModel(b)).ToList();
            return View(oldBookingsElements);
        }

        [HttpGet]
        public ActionResult ActiveBookings()
        {
            List<BookingModel> activeBookings = _bookingService.GetActiveBookings(6);//CurrentUser.Id
            List<BookingElementViewModel> activeBookingsElements = activeBookings?.Select(b => BookingMappings.MapBookingModelToViewModel(b)).ToList();
            return View(activeBookingsElements);
        }

        [HttpGet]
        public ActionResult CancelBooking(int id)
        {
            bool canceled = _bookingService.CancelBooking(id);
            if (canceled)
                TempData["Result"] = "Booking successfully canceled !";
            else
                TempData["Result"] = "Booking could not be canceled !";
            return RedirectToAction("ActiveBookings");
        }

        [HttpGet]
        public ActionResult FilterRooms()
        {
            List<FacilityModel> Facilities = _facilityService.GetFacilites();
            List<RoomCategoryModel> RoomCategories = _roomCategoryService.GetRoomCategories();
            FilterRoomViewModel model = new FilterRoomViewModel();
            model.Facilities = Facilities;
            model.Categories = RoomCategories;

            return View(model);
        }
        [HttpPost]
        public ActionResult FilterRooms(FilterRoomViewModel filterModel)
        {
            if(ModelState.IsValid)
            {
                FilterRoomModel roomsFilter = RoomMappings.MapFilterRoomViewModelToFRModel(filterModel);
                List<RoomModel> filteredRooms = _roomService.FilterRooms(roomsFilter);
                filterModel.Rooms = filteredRooms;
            }
            List<FacilityModel> Facilities = _facilityService.GetFacilites();
            List<RoomCategoryModel> RoomCategories = _roomCategoryService.GetRoomCategories();
            filterModel.Categories = RoomCategories;
            filterModel.Facilities = Facilities;
            return View(filterModel);
        }

        [HttpGet]
        public ActionResult AddFacility(int id)
        {
            BookingModel bookingModel = _bookingService.GetBookingById(id);
            if (bookingModel == null)
                return RedirectToAction("ActiveBookings");
            List<FacilityModel> Facilities = _facilityService.GetFacilites();

            BookingViewModel bookingViewModel = BookingMappings.MapBookingModelToBookingViewModel(bookingModel);
            AddFacilityViewModel model = new AddFacilityViewModel();
            model.Booking = bookingViewModel;
            model.Facilities = Facilities;

            return View(model);
        }

        [HttpPost]
        public ActionResult AddFacility(AddFacilityViewModel model)
        {
            if (ModelState.IsValid)
            {
                ExtraFacilityModel efModel = FacilityMappings.MapFacilityViewModelToEFacilityModel(model);
                if (_facilityService.AddExtraFacility(efModel))
                    ViewBag.Result = "Facility successfully added !";
                else
                    ViewBag.Result = "Facility could not be added !";
            }
            BookingModel bookingModel = _bookingService.GetBookingById(model.Booking.Id);
            List<FacilityModel> Facilities = _facilityService.GetFacilites();
            BookingViewModel bookingViewModel = BookingMappings.MapBookingModelToBookingViewModel(bookingModel);
            model.Booking = bookingViewModel;
            model.Facilities = Facilities;
            return View(model);
            
        }

        [HttpGet]
        public ActionResult AddService(int id)
        {
            BookingModel bookingModel = _bookingService.GetBookingById(id);
            if (bookingModel == null)
                return RedirectToAction("ActiveBookings");
            BookingViewModel bookingViewModel = BookingMappings.MapBookingModelToBookingViewModel(bookingModel);
            AddDriverServiceViewModel model = new AddDriverServiceViewModel();
            model.Booking = bookingViewModel;

            return View(model);
        }
        
        [HttpPost]
        public ActionResult AddService(AddDriverServiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool success = _driverService.AddDriverService(DriverServiceMappings.MapAddDSViewModelToDriverServiceModel(model));
                if (success)
                {
                    ViewBag.Result = "Driver service successfully added !";
                }
                else
                {
                    ViewBag.Result = "Driver service could not be added !";
                }
            }
            BookingModel bookingModel = _bookingService.GetBookingById(model.Booking.Id);
            BookingViewModel bookingViewModel = BookingMappings.MapBookingModelToBookingViewModel(bookingModel);
            AddDriverServiceViewModel returnModel = new AddDriverServiceViewModel();
            returnModel.Booking = bookingViewModel;
            return View(returnModel);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            BookingModel bookingModel = _bookingService.GetBookingById(id);
            if (bookingModel == null)
                return RedirectToAction("OldBookings");
            BookingViewModel bookingViewModel = BookingMappings.MapBookingModelToBookingViewModel(bookingModel);
            BookingDetailsViewModel model = new BookingDetailsViewModel();
            model.bookingModel = bookingViewModel;
            model.ratingModel = bookingModel.Rating != null ? RatingMappings.MapRatingToRatingViewModel(bookingModel.Rating) : null;
            return View(model);
        }

        [HttpPost]
        public ActionResult AddRating(BookingDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                RatingViewModel ratingModel = model.ratingModel;
                int bookingId = model.bookingModel.Id;
                ratingModel.BookingId = bookingId;
                RatingModel RatingModel = RatingMappings.MapRatingViewModelToRatingModel(ratingModel);
                _ratingService.AddBookingRating(RatingModel);
            }

            return RedirectToAction("Details", new { id = model.bookingModel.Id });
        }

        [HttpGet]
        public ActionResult CreateBooking()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateBooking(CreateBookingViewModel model)
        {
            if(ModelState.IsValid)
            {
                if (model.EndDate < model.StartDate)
                    ViewBag.Result = "End date should be equal or greater than start date !";
                else
                {
                    BookingModel bookingModel = BookingMappings.MapCreateBookingVModelToBookingModel(model);
                    bookingModel.ClientId = 6; //CurrentUser.Id
                    int id = _bookingService.CreateNewBooking(bookingModel);
                    return RedirectToAction("ChooseRooms", new { bookingId = id });
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult ChooseRooms(int bookingId)
        {
            BookingModel booking = _bookingService.GetBookingById(bookingId);
            List<RoomModel> freeRooms = _roomService.GetFreeRoomsForBooking(bookingId);
            List<FacilityModel> roomFacilites = _facilityService.GetFacilites();
            ChooseRoomViewModel model = new ChooseRoomViewModel();
            model.rooms = freeRooms;
            model.booking = booking;
            model.facilities = roomFacilites;
            return View(model);

        }

        [HttpPost]
        public ActionResult ChooseRooms(ChooseRoomViewModel model)
        {
            
            if(ModelState.IsValid)
            {
                ChooseRoomModel ChooseModel = BookingMappings.MapChooseRoomViewModelToChooseRoomModel(model);
                if(_bookingService.AddRoomForBooking(ChooseModel))
                {
                    ViewBag.Result = "Room successfully added !";
                }
                else
                {
                    ViewBag.Result = "Room could not be added !";
                }
            }
            var returnModel = new ChooseRoomViewModel();

M19G1/Views/Clients/ActiveBookings.cshtml
@model IEnumerable<M19G1.Models.BookingElementViewModel>

<p>
    @Html.ActionLink("Create New", "CreateBooking")
</p>
<p>
    <h3>@TempData["Result"]</h3>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomList)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rate)
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RoomList)
                </td>
                <td>
                    @if (item.rate < 0)
                    {
                        <text>"Not rated"</text>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.rate)
                    }
                    
                </td>
                <td>
                    @Html.ActionLink("Add Facility", "AddFacility", new { id = item.Id }, new { @class = "btn btn-success" }) 
                    @Html.ActionLink("Add DriverService", "AddService",new { id = item.Id}, new { @class = "btn btn-success" }) 
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
                    @if (item.Cancelable)
                    {
                        <text> | </text>
                        @Html.ActionLink("  Cancel", "CancelBooking", new { id = item.Id })
                    }

                </td>
            </tr>
        }}

</table>

M19G1/Views/Clients/AddFacility.cshtml
@model M19G1.Models.AddFacilityViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@ViewBag.Result</h4>
        <h5>Booking details :</h5>
        <div class="form-group">
            @Html.LabelFor(model => model.Booking.StartDate, htmlAttributes: new { @class = "control-label col-md-1" })
            <text> :   </text>
            @Html.DisplayFor(model => model.Booking.StartDate)
            <text>  |  </text>
            @Html.LabelFor(model => model.Booking.EndDate, htmlAttributes: new { @class = "control-label col-md-1" })
            <text> :   </text>
            @Html.DisplayFor(model => model.Booking.EndDate)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Booking.Rooms, htmlAttributes: new { @class = "control-label col-md-1" })
            <text> : </text>
            @foreach (var room in Model.Booking.Rooms)
            {
                    @Html.DisplayFor(item => room.Name) <text> | </text>
            }
        </div>
    </div>

    <div class="form-horizontal">
        <h4>Add Facility </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Booking.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoomId, new SelectList(Model.Booking.Rooms, "RoomId", "Name"))
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FacilityId, new SelectList(Model.Facilities, "FacilityId", "FacilityName"))
                @Html.ValidationMessageFor(model => model.FacilityId, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.FacilityQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityQuantity, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Facility" class="btn btn-default" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to bookings", "ActiveBookings")
</div>

M19G1/Views/Clients/ChooseRooms.cshtml
@model M19G1.Models.ChooseRoomViewModel

@using (Html.BeginForm("ChooseRooms","Clients",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.booking.Id)
    <h4> @ViewBag.Result </h4>

    <div class="form-horizontal">
        <h5>Booking details :</h5>
        <div class="form-group">
            @Html.LabelFor(model => model.booking.Start, htmlAttributes: new { @class = "control-label col-md-1" })
            <text> :   </text>
            @Html.DisplayFor(model => model.booking.Start)
            <text>  |  </text>
            @Html.LabelFor(model => model.booking.End, htmlAttributes: new { @class = "control-label col-md-1" })
            <text> :   </text>
            @Html.DisplayFor(model => model.booking.End)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.booking.BookingRooms, htmlAttributes: new { @class = "control-label col-md-2" })
            <text> : </text>
            @if (Model.booking.BookingRooms != null)
            {
                foreach (var bookingRoom in Model.booking.BookingRooms)
                {
                    @Html.DisplayFor(item => bookingRoom.Room.RoomName) <text> with </text>
                    @Html.DisplayFor(item => bookingRoom.Room.GuestsNr)
                    <text> guests  | </text>
                }
            }
            else
            {
                 <text> No rooms yet ! </text>
            }

        </div>
    </div>
    <div class="form-horizontal">
        <h4>Choose Room</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoomId, new SelectList(Model.rooms, "Id", "RoomName"), new { @class = "btn btn-default dropdown-toggle" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.facilityIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.facilityIds, new MultiSelectList(Model.facilities, "FacilityId", "FacilityName"), new { @class = "multiselect form-control", multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.facilityIds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add room" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
@using (Html.BeginForm("FinishBooking", "Clients", new { id = Model.booking.Id }))
{
   <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Finish booking" class="btn btn-primary" />
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

M19G1/Views/Clients/Details.cshtml
@model M19G1.Models.BookingDetailsViewModel

@using (Html.BeginForm("AddRating", "Clients"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.bookingModel.Id)
    <div class="form-horizontal">
        <h4>Booking Details </h4>
        <hr />
        <dl class="dl-horizontal"></dl>
    </div>
    <h4>@ViewBag.Result</h4>
    <div class="form-group">
        @Html.LabelFor(model => model.bookingModel.StartDate, htmlAttributes: new { @class = "control-label col-md-1.5" })
        <text> :   </text>
        @Html.DisplayFor(model => model.bookingModel.StartDate)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.bookingModel.EndDate, htmlAttributes: new { @class = "control-label col-md-1.5" })
        <text> :   </text>
        @Html.DisplayFor(model => model.bookingModel.EndDate)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.bookingModel.CheckInTime, htmlAttributes: new { @class = "control-label col-md-1.5" })
        <text> :   </text>
        @if (Model.bookingModel.CheckInTime == null)
        {
            <text> Not checked in ! </text>
        }
        else
        {
            @Html.DisplayFor(model => model.bookingModel.CheckInTime)
        }
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.bookingModel.CheckOutTime, htmlAttributes: new { @class = "control-label col-md-1.5" })
        <text> :   </text>
        @if (Model.bookingModel.CheckOutTime == null)
        {
            <text> Not checked out ! </text>
        }
        else
        {
            @Html.DisplayFor(model => model.bookingModel.CheckOutTime)
        }
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.bookingModel.Rooms, htmlAttributes: new { @class = "control-label col-md-1" })
        <text> : </text>
        @foreach (var room in Model.bookingModel.Rooms)
        {

            <div>
                @Html.DisplayFor(item => room.Name) <text> with </text>
                @Html.DisplayFor(item => room.GuestsNr) <text> guests. </text>
            </div>
        }
    </div>
        <div class="form-group">
            @Html.LabelFor(model => model.bookingModel.DriverServices, htmlAttributes: new { @class = "control-label col-md-1.5" })
            <text> : </text>
            @if (Model.bookingModel.DriverServices.Count() != 0)
            {
                foreach (var ds in Model.bookingModel.DriverServices)
                {
                    <div>
                        <text>
                            Location :
                        </text>
                        @Html.DisplayFor(item => ds.Location) <text> at time  </text>
                        @Html.DisplayFor(item => ds.PickUpTime)
                    </div>
                }
            }
            else
            {
               <text> There are no driver services </text>
            }
        </div>
    if (Model.ratingModel != null)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.ratingModel.Rate, htmlAttributes: new { @class = "control-label col-md-1.5" })
            <text> :  </text>
            @Html.DisplayFor(model => model.ratingModel.Rate)
        </div>
        if (Model.ratingModel.Description != null)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.ratingModel.Description, htmlAttributes: new { @class = "control-label col-md-1.5" })
                <text> :  </text>
                @Html.DisplayFor(model => model.ratingModel.Description)
            </div>
        }

    }
    else
    {
        <div class="form-group">
            @Html.LabelFor(model => model.ratingModel.Rate, htmlAttributes: new { @class = "control-label col-md-1.5" })
            <text> :  </text>
            @Html.EditorFor(model => model.ratingModel.Rate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ratingModel.Rate, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ratingModel.Description, htmlAttributes: new { @class = "control-label col-md-1.5" })
            <text> :  </text>
            @Html.TextAreaFor(model => model.ratingModel.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ratingModel.Description, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Rating" class="btn btn-default" />
            </div>
        </div>
    }
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
}

M19G1/Views/Clients/RoomDetails.cshtml
@model M19G1.Models.RoomDetailsViewModel

<div>
    <h4>RoomDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuestsNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestsNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomDescription)
        </dd>
        <dt>
            @Html.Display("Category")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoomCategory.CatName)
        </dd>
    </dl>
</div>


@if (Model.RoomFacilities != null)
{
    if (Model.RoomFacilities.Count > 0)
    {
        <div>
            <table id="myTable">
                <thead>
                    <tr>
                        <th>Facility Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.RoomFacilities)
                    {
                        <tr>
                            <td>
                                @item.Facility.FacilityName
                            </td>
                            <td>
                                @item.Facility.Description
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
}
<div>
    @Html.ActionLink("Back to Filter", "FilterRooms")
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
}